package org.example.modal;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;
import org.example.dto.order.OrderItem;
import org.example.dto.order.ShippingAddress;

import java.util.List;

@Data
@DynamoDBTable(tableName = "order")
public class Order {


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private List<OrderItem> items;

    @DynamoDBAttribute
    private ShippingAddress shippingAddress;

    @DynamoDBAttribute
    private String paymentMethod;

    @DynamoDBAttribute
    private double totalAmount;

    @DynamoDBAttribute
    private String orderStatus;

    @DynamoDBAttribute
    private String createdAt;

    @DynamoDBAttribute
    private String user; //email buyer

}




