spring:
  application:
    name: Storage-Backend
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  data:
    mongodb:
      uri: ${MONGODB_CLOUD_URI}
      database: ${DB_NAME}

jwt:
  secret: BV5vljmTbb5mXqzLfED6tXD1P40061PSIELOiDJ1CEC


video:
  upload:
    dir: ${DIR:../deployment/videos}
  base-path: ${BASE_PATH:E:/ecommerce/Storage-Live/deployment/videos}


cloud:
  aws:
    credentials:
      access-key: ${CLOUD_ACCESS_KEY}
      secret-key: ${CLOUD_SECRET_KEY}
    region:
      static: ${CLOUD_REGION}
    stack:
      auto: false

app:
  s3:
    bucket: ${BUCKET_NAME}

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_SECRET_KEY}
