# Reduce logging level to make sure the application works with SAM local
# https://github.com/aws/serverless-java-container/issues/134
logging.level.root=WARN


cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION}
cloud.aws.stack.auto=false
app.s3.bucket=${BUCKET_NAME}
cloud.aws.serviceEndPoint=${AWS_SERVICE_END_POINT}
cloud.aws.singingRegion=${AWS_REGION}

jwt.secret=ThisIsMyJwtSecretKey123456789ABCDEF


spring.servlet.multipart.enabled=true
# Maximum file size allowed for a single file upload
spring.servlet.multipart.max-file-size=1000MB

# Maximum request size allowed for multipart/form-data requests
spring.servlet.multipart.max-request-size=1000MB


#for image-upload
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_NAME}
cloudinary.api-secret=${CLOUDINARY_SECRET}




